# --- FREETYPE2 ---

# CFlags
list(APPEND FREETYPE_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/include)
list(APPEND FREETYPE_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/scripts/freetype)

# Build CFlags
list(APPEND FREETYPE_DEFINES FT_CONFIG_MODULES_H=\"slimftmodules.h\")
list(APPEND FREETYPE_DEFINES FT_CONFIG_OPTIONS_H=\"slimftoptions.h\")
list(APPEND FREETYPE_DEFINES FT2_BUILD_LIBRARY)

# Source Files
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftbase.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftbbox.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftbitmap.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftdebug.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftfstype.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftgasp.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftglyph.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftinit.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftstroke.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftsynth.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/ftsystem.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/base/fttype1.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/cff/cff.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/cid/type1cid.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/psaux/psaux.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/pshinter/pshinter.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/psnames/psnames.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/raster/raster.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/sfnt/sfnt.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/smooth/smooth.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/truetype/truetype.c)
list(APPEND FREETYPE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freetype/src/type1/type1.c)

# --- GUMBO ---

# Include
list(APPEND GUMBO_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src)

# Build CFlags
list(APPEND GUMBO_BUILD_CFLAGS -std=c99)

# Source Files
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/attribute.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/char_ref.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/error.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/parser.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/string_buffer.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/string_piece.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/tag.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/tokenizer.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/utf8.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/util.c)
list(APPEND GUMBO_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/gumbo-parser/src/vector.c)

# --- HARFBUZZ ---

# CFlags
list(APPEND HARFBUZZ_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src)
list(APPEND HARFBUZZ_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/include/mupdf)
list(APPEND HARFBUZZ_INCLUDE ${FREETYPE_INCLUDE})

# Build CFlags
list(APPEND HARFBUZZ_DEFINES HAVE_FALLBACK=1)
list(APPEND HARFBUZZ_DEFINES HAVE_FREETYPE)
list(APPEND HARFBUZZ_DEFINES HAVE_OT)
list(APPEND HARFBUZZ_DEFINES HAVE_ROUND)
list(APPEND HARFBUZZ_DEFINES HAVE_UCDN)
list(APPEND HARFBUZZ_DEFINES HB_NO_MT)
list(APPEND HARFBUZZ_DEFINES hb_malloc_impl=fz_hb_malloc)
list(APPEND HARFBUZZ_DEFINES hb_calloc_impl=fz_hb_calloc)
list(APPEND HARFBUZZ_DEFINES hb_free_impl=fz_hb_free)
list(APPEND HARFBUZZ_DEFINES hb_realloc_impl=fz_hb_realloc)
list(APPEND HARFBUZZ_DEFINES HB_NO_PRAGMA_GCC_DIAGNOSTIC)

list(APPEND HARFBUZZ_BUILD_CFLAGS -w)
list(APPEND HARFBUZZ_BUILD_CFLAGS -fno-exceptions)
list(APPEND HARFBUZZ_BUILD_CFLAGS -fno-rtti)
list(APPEND HARFBUZZ_BUILD_CFLAGS -fno-threadsafe-statics)
list(APPEND HARFBUZZ_BUILD_CFLAGS -fvisibility-inlines-hidden)
list(APPEND HARFBUZZ_BUILD_CFLAGS -std=c++17)

# Source Files
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/graph/gsubgpos-context.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-aat-layout.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-aat-map.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-blob.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-buffer.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-buffer-verify.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-buffer-serialize.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-common.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-face.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-fallback-shape.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-font.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ft.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-map.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-number.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-cff1-table.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-cff2-table.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-color.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-face.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-font.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-layout.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-map.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-math.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-meta.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-metrics.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-name.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shape.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shape-fallback.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shape-normalize.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-arabic.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-default.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-hangul.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-hebrew.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-indic.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-indic-table.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-khmer.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-myanmar.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-syllabic.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-thai.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-use.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-shaper-vowel-constraints.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-tag.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ot-var.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-set.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-shape.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-shape-plan.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-shaper.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-static.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset-cff1.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset-cff2.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset-cff-common.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset-input.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-subset-plan.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-ucd.cc)
list(APPEND HARFBUZZ_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/harfbuzz/src/hb-unicode.cc)

# --- LIBJPEG ---

# CFlags
list(APPEND LIBJPEG_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg)
list(APPEND LIBJPEG_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/scripts/libjpeg)

# Source Files
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jaricom.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcapimin.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcapistd.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcarith.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jccoefct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jccolor.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcdctmgr.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jchuff.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcinit.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcmainct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcmarker.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcmaster.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcomapi.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcparam.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcprepct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jcsample.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdapimin.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdapistd.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdarith.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdatadst.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdatasrc.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdcoefct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdcolor.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jddctmgr.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdhuff.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdinput.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdmainct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdmarker.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdmaster.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdmerge.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdpostct.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdsample.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jdtrans.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jerror.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jfdctflt.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jfdctfst.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jfdctint.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jidctflt.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jidctfst.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jidctint.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jmemmgr.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jquant1.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jquant2.c)
list(APPEND LIBJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libjpeg/jutils.c)

# --- LCMS2 (multi-threaded fork) ---

# CFlags
list(APPEND LCMS2_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/include)

list(APPEND LCMS2_DEFINES HAVE_LCMS2MT)

# Source Files
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsalpha.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmscam02.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmscgats.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmscnvrt.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmserr.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsgamma.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsgmt.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmshalf.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsintrp.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsio0.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsio1.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmslut.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsmd5.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsmtrx.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsnamed.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsopt.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmspack.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmspcs.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsplugin.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsps2.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmssamp.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmssm.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmstypes.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsvirt.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmswtpnt.c)
list(APPEND LCMS2_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lcms2/src/cmsxform.c)

# --- MUJS ---

# CFlags
list(APPEND MUJS_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/mujs)

# Source Files
list(APPEND MUJS_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/mujs/one.c)

# --- ZLIB ---

# CFlags
list(APPEND ZLIB_CFLAGS -I${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib)

# Build CFlags
list(APPEND ZLIB_DEFINES HAVE_UNISTD_H)
list(APPEND ZLIB_DEFINES HAVE_STDARG_H)

# Source Files
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/adler32.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/compress.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/crc32.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/deflate.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/inffast.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/inflate.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/inftrees.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/trees.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/uncompr.c)
list(APPEND ZLIB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/zlib/zutil.c)

# --- JBIG2DEC ---

# CFlags
list(APPEND JBIG2DEC_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec)
list(APPEND JBIG2DEC_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/include)

# Build CFlags
list(APPEND JBIG2DEC_DEFINES HAVE_STDINT_H)
list(APPEND JBIG2DEC_DEFINES JBIG_EXTERNAL_MEMENTO_H=\"mupdf/memento.h\")

# Source Files
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_arith.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_arith_iaid.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_arith_int.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_generic.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_halftone.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_huffman.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_hufftab.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_image.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_mmr.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_page.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_refinement.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_segment.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_symbol_dict.c)
list(APPEND JBIG2DEC_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/jbig2dec/jbig2_text.c)

# --- OPENJPEG ---

# CFlags
list(APPEND OPENJPEG_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2)

# Build CFlags
list(APPEND OPENJPEG_DEFINES OPJ_STATIC)
list(APPEND OPENJPEG_DEFINES OPJ_HAVE_INTTYPES_H)
list(APPEND OPENJPEG_DEFINES OPJ_HAVE_STDINT_H)
list(APPEND OPENJPEG_DEFINES MUTEX_pthread=0)

# Source Files
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/bio.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/cio.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/dwt.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/event.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/function_list.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/ht_dec.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/image.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/invert.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/j2k.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/jp2.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/mct.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/mqc.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/openjpeg.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/pi.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/sparse_array.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/t1.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/t2.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/tcd.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/tgt.c)
list(APPEND OPENJPEG_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/openjpeg/src/lib/openjp2/thread.c)

# --- FREEGLUT ---

# CFlags
list(APPEND GLUT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/include)
list(APPEND GLUT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src)

# Build CFlags
list(APPEND GLUT_DEFINES HAVE_UNISTD_H)
list(APPEND GLUT_DEFINES HAVE_STDINT_H)
list(APPEND GLUT_DEFINES HAVE_X11_EXTENSIONS_XRANDR_H)

# Source Files
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_callbacks.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_cursor.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_display.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_ext.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_font.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_font_data.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_gamemode.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_geometry.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_gl2.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_init.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_input_devices.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_joystick.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_main.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_menu.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_misc.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_overlay.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_spaceball.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_state.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_stroke_mono_roman.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_stroke_roman.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_structure.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_teapot.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_videoresize.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/fg_window.c)

list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_cursor_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_display_x11_glx.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_ext_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_gamemode_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_glutfont_definitions_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_init_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_input_devices_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_joystick_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_main_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_menu_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_spaceball_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_state_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_state_x11_glx.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_structure_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_window_x11.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_window_x11_glx.c)
list(APPEND GLUT_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/freeglut/src/x11/fg_xinput_x11.c)

# Libraries
list(APPEND GLUT_LIBS -lGL)
list(APPEND GLUT_LIBS -lX11)
list(APPEND GLUT_LIBS -lXrandr)

# --- LEPTONICA (optional, used by Tesseract) ---

# CFlags
list(APPEND LEPTONICA_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src)
list(APPEND LEPTONICA_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/scripts/tesseract)

# Build CFlags
list(APPEND LEPTONICA_DEFINES LEPTONICA_INTERCEPT_ALLOC=1)
list(APPEND LEPTONICA_DEFINES HAVE_LIBPNG=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBTIFF=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBJPEG=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBZ=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBGIF=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBUNGIF=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBWEBP=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBWEBP_ANIM=0)
list(APPEND LEPTONICA_DEFINES HAVE_LIBJP2K=0)

list(APPEND LEPTONICA_BUILD_CFLAGS -Wno-address-of-packed-member)

# Source Files
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/adaptmap.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/affine.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/affinecompose.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/arrayaccess.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/baseline.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bbuffer.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bilateral.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bilinear.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/binarize.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/binexpand.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/binreduce.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/blend.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bmf.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bmpio.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bmpiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bootnumgen1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bootnumgen2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bootnumgen3.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bootnumgen4.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxbasic.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxfunc1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxfunc2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxfunc3.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxfunc4.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/boxfunc5.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/bytearray.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ccbord.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ccthin.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/classapp.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colorcontent.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/coloring.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colormap.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colormorph.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colorquant1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colorquant2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colorseg.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/colorspace.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/compare.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/conncomp.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/convertfiles.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/convolve.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/correlscore.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dewarp1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dewarp2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dewarp3.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dewarp4.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dnabasic.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dnafunc1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dnahash.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dwacomb.2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/dwacomblow.2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/edge.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/encoding.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/enhance.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fhmtauto.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fhmtgenlow.1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fmorphauto.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fmorphgen.1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fmorphgenlow.1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fpix1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/fpix2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/gifiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/gplot.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/graphics.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/graymorph.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/grayquant.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/hashmap.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/heap.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/jbclass.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/jp2kheader.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/jp2kheaderstub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/jp2kiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/jpegiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/kernel.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/libversions.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/list.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/map.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/morph.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/morphapp.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/morphdwa.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/morphseq.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/numabasic.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/numafunc1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/numafunc2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pageseg.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/paintcmap.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/partify.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/partition.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pdfio1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pdfio1stub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pdfio2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pdfio2stub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pix1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pix2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pix3.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pix4.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pix5.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixabasic.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixacc.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixafunc1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixafunc2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixalloc.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixarith.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixcomp.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixconv.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixlabel.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pixtiling.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pngiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/pnmio.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/projective.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/psio1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/psio1stub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/psio2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/psio2stub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ptabasic.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ptafunc1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ptafunc2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/ptra.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/quadtree.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/queue.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rank.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rbtree.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/readfile.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/regutils.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rop.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/roplow.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rotate.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rotateam.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rotateorth.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/rotateshear.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/runlength.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/sarray1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/sarray2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/scale1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/scale2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/seedfill.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/sel1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/sel2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/selgen.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/shear.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/skew.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/spixio.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/stack.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/stringcode.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/strokes.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/textops.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/tiffiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/utils1.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/utils2.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/warper.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/webpiostub.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/writefile.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/zlibmem.c)
list(APPEND LEPTONICA_SRC ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/leptonica/src/zlibmemstub.c)

# --- TESSERACT (optional) ---

list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/include)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/classify)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/viewer)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/wordrec)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/cutil)
list(APPEND TESSERACT_INCLUDE ${CMAKE_CURRENT_SOURCE_DIR}/scripts/tesseract)
list(APPEND TESSERACT_INCLUDE ${LEPTONICA_INCLUDE})

list(APPEND TESSERACT_DEFINES TESSERACT_IMAGEDATA_AS_PIX)
list(APPEND TESSERACT_DEFINES TESSERACT_DISABLE_DEBUG_FONTS)
list(APPEND TESSERACT_DEFINES GRAPHICS_DISABLED)
list(APPEND TESSERACT_DEFINES DISABLED_LEGACY_ENGINE)

list(APPEND TESSERACT_LANGFLAGS "-std=c++17")
list(APPEND TESSERACT_BUILD_CFLAGS ${TESSERACT_LANGFLAGS})

list(APPEND TESSERACT_LIBS "-lpthread")
list(APPEND TESSERACT_LIBS "-lstdc++")

list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/altorenderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/baseapi.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/capi.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/hocrrenderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/lstmboxrenderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/pdfrenderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/renderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/api/wordstrboxrenderer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/dotproduct.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/dotproductneon.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/intsimdmatrix.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/simddetect.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/applybox.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/control.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/linerec.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/ltrresultiterator.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/mutableiterator.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/output.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/pageiterator.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/pagesegmain.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/pagewalk.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/paragraphs.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/paramsd.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/pgedit.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/reject.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/resultiterator.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/tessedit.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/tesseractclass.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/tessvars.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/thresholder.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccmain/werdit.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/blamer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/blobbox.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/blobs.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/blread.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/boxread.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/boxword.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/ccstruct.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/coutln.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/detlinefit.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/dppoint.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/image.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/imagedata.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/linlsq.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/matrix.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/mod128.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/normalis.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/ocrblock.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/ocrpara.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/ocrrow.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/otsuthr.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/pageres.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/pdblock.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/points.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/polyaprx.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/polyblk.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/quadlsq.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/quspline.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/ratngs.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/rect.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/rejctmap.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/seam.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/split.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/statistc.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/stepblob.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccstruct/werd.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/ccutil.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/clst.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/elst.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/elst2.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/errcode.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/params.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/scanutils.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/serialis.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/tessdatamanager.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/tprintf.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/unichar.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/unicharcompress.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/unicharmap.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/ccutil/unicharset.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/classify/classify.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/context.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/dawg.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/dawg_cache.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/dict.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/permdawg.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/stopper.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/dict/trie.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/convolve.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/fullyconnected.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/functions.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/input.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/lstm.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/lstmrecognizer.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/maxpool.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/network.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/networkio.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/parallel.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/plumbing.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/recodebeam.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/reconfig.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/reversed.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/series.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/stridemap.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/tfnetwork.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/lstm/weightmatrix.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/alignedblob.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/baselinedetect.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/bbgrid.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/blkocc.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/blobgrid.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/ccnontextdetect.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/cjkpitch.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/colfind.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/colpartition.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/colpartitiongrid.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/colpartitionset.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/devanagari_processing.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/drawtord.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/edgblob.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/edgloop.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/fpchop.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/gap_map.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/imagefind.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/linefind.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/makerow.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/oldbasel.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/pithsync.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/pitsync1.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/scanedg.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/sortflts.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/strokewidth.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tabfind.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tablefind.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tablerecog.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tabvector.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/textlineprojection.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/textord.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/topitch.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tordmain.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tospace.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/tovars.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/underlin.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/wordseg.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/textord/workingpartset.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/viewer/scrollview.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/viewer/svmnode.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/viewer/svutil.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/wordrec/tface.cpp")
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/wordrec/wordrec.cpp")

if (HAVE_AVX)
    list(APPEND TESSERACT_DEFINES HAVE_AVX __AVX__)
    list(APPEND TESSERACT_BUILD_CFLAGS "-mavx")
    list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/dotproductavx.cpp")
endif ()

if (HAVE_AVX2)
    list(APPEND TESSERACT_DEFINES HAVE_AVX2 __AVX2__)
    list(APPEND TESSERACT_BUILD_CFLAGS "-mavx2")
    list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/intsimdmatrixavx2.cpp")
endif ()

if (HAVE_FMA)
    list(APPEND TESSERACT_DEFINES HAVE_FMA __FMA__)
    list(APPEND TESSERACT_BUILD_CFLAGS "-mfma")
    list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/dotproductfma.cpp")
endif ()

if (HAVE_SSE4_1)
    list(APPEND TESSERACT_DEFINES HAVE_SSE4_1 __SSE4_1__)
    list(APPEND TESSERACT_BUILD_CFLAGS "-msse4.1")
    list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/dotproductsse.cpp")
    list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/intsimdmatrixsse.cpp")
endif ()

if (HAVE_NEON)
    list(APPEND TESSERACT_DEFINES HAVE_NEON)
endif ()

# Always include the neon code - it will compile to nothing if
# neon isn't enabled. We need to always include it, because it
# will be used if __aarch64__ is defined, which implies the
# presence of NEON even without the HAVE_NEON flags.
list(APPEND TESSERACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/tesseract/src/arch/intsimdmatrixneon.cpp")

# --- EXTRACT ---

list(APPEND EXTRACT_INCLUDE "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/include")
list(APPEND EXTRACT_INCLUDE "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src")

list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/alloc.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/astring.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/boxer.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/buffer.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/document.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/docx.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/docx_template.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/extract.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/join.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/json.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/mem.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/html.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/odt.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/odt_template.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/outf.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/rect.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/sys.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/text.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/xml.c")
list(APPEND EXTRACT_SRC "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/extract/src/zip.c")